global:
  scrape_interval: 1s
  evaluation_interval: 1s

scrape_configs:
  - job_name: 'gateway-service'
    static_configs:
      - targets: ['gateway-service:8000']

  - job_name: 'inventory-service'
    static_configs:
      - targets: ['inventory-service:8001']

  - job_name: 'warehouse-service'
    static_configs:
      - targets: ['warehouse-service:8002']
